language: perl
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
env:
  global:
    secure: "Q4ANWyMsFfZkH8XUxl4Cfe/tvzYFXcpaangsTe/80ElkjdRFd/YIcBuIkWQ/rUiiCR1VPrr5mfv/RD8P8Uu/Smz9a+i/33RVR1/404PQUHQp5XPxayhthmqC/KqJL4OlVBHlEpDwGh4YK285ogYvQzqvZXvEU6Tq/WZVhTtS9b8="
after_success:
  - curl https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
